---
- name: add mongo repo
  copy:
    src: files/mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb package
  yum:
    name: mongodb-org
    state: present
  notify: restart mongodb

- name: copy config file
  template:
    src: templates/mongod.conf
    dest: /etc/mongod.conf
  notify: restart mongodb

- name: check if firewall is installed
  shell: command -v firewall-cmd >/dev/null
  register: firewall_is_installed
  failed_when: no
  changed_when: no

- name: open mongodb port
  firewalld:
    service: mongodb
    zone: public
    permanent: yes
    immediate: yes
    state: enabled
  when: firewall_is_installed.rc == 0
